name: pokedex
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.6
  google_fonts: ^3.0.1
  flutter_simple_dependency_injection: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  http: ^0.13.3
  cached_network_image: ^3.2.1
  cached_network_image_platform_interface: ^1.0.0
  json_annotation: ^4.6.0
  sliding_up_panel: ^2.0.0+1
  flutter_dropdown: ^1.0.1+hotfix.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - contents/images/
  uses-material-design: true

