enum PokemonTypes {
  grass,
  poison,
  fire,
  flying,
  water,
  bug,
  normal,
  electric,
  ground,
  fairy,
  fighting,
  psychic,
  rock,
  steel,
  ice,
  ghost,
  dragon,
  dark,
  monster,
  unknown,
}

const List<String> types = [
  'Grass',
  'Poison',
  'Fire',
  'Flying',
  'Water',
  'Bug',
  'Normal',
  'Electric',
  'Ground',
  'Fairy',
  'Fighting',
  'Psychic',
  'Rock',
  'Steel',
  'Ice',
  'Ghost',
  'Dragon',
  'Dark',
  // 'Monster',
];

final pokemonEffectivenessMap = <String, Map<String, double>>{
  'Normal': {
    'Ghost': 0,
    'Fighting': 2,
  },
  'Fire': {
    'Bug': 0.5,
    'Fairy': 0.5,
    'Fire': 0.5,
    'Grass': 0.5,
    'ice': 0.5,
    'Steel': 0.5,
    'Ground': 2,
    'Rock': 2,
    'Water': 2,
  },
  'Water': {
    'Fire': 0.5,
    'Ice': 0.5,
    'Steel': 0.5,
    'Water': 0.5,
    'Electric': 2,
    'Grass': 2,
  },
  'Electric': {
    'Electric': 0.5,
    'Flying': 0.5,
    'Steel': 0.5,
    'Ground': 2,
  },
  'Grass': {
    'Electric': 0.5,
    'Grass': 0.5,
    'Ground': 0.5,
    'Water': 0.5,
    'Bug': 2,
    'Ice': 2,
    'Flying': 2,
    'Fire': 2,
    'Poison': 2,
  },
  // PokemonTypes.ice: {
  //   PokemonTypes.ice: 0.5,
  //   PokemonTypes.fire: 2,
  //   PokemonTypes.fighting: 2,
  //   PokemonTypes.rock: 2,
  //   PokemonTypes.steel: 2,
  // },
  // PokemonTypes.fighting: {
  //   PokemonTypes.bug: 0.5,
  //   PokemonTypes.rock: 0.5,
  //   PokemonTypes.dark: 0.5,
  //   PokemonTypes.flying: 2,
  //   PokemonTypes.psychic: 2,
  //   PokemonTypes.fairy: 2,
  // },
  // PokemonTypes.poison: {
  //   PokemonTypes.fighting: 0.5,
  //   PokemonTypes.poison: 0.5,
  //   PokemonTypes.bug: 0.5,
  //   PokemonTypes.fairy: 0.5,
  //   PokemonTypes.ground: 2,
  //   PokemonTypes.psychic: 2,
  // },
  // PokemonTypes.ground: {
  //   PokemonTypes.electric: 0,
  //   PokemonTypes.poison: 0.5,
  //   PokemonTypes.rock: 0.5,
  //   PokemonTypes.water: 2,
  //   PokemonTypes.grass: 2,
  //   PokemonTypes.ice: 2,
  // },
  // PokemonTypes.flying: {
  //   PokemonTypes.ground: 0,
  //   PokemonTypes.grass: 0.5,
  //   PokemonTypes.fighting: 0.5,
  //   PokemonTypes.bug: 0.5,
  //   PokemonTypes.electric: 2,
  //   PokemonTypes.ice: 2,
  //   PokemonTypes.rock: 2,
  // },
  // PokemonTypes.psychic: {
  //   PokemonTypes.fighting: 0.5,
  //   PokemonTypes.psychic: 0.5,
  //   PokemonTypes.bug: 2,
  //   PokemonTypes.ghost: 2,
  //   PokemonTypes.dark: 2,
  // },
  // PokemonTypes.bug: {
  //   PokemonTypes.grass: 0.5,
  //   PokemonTypes.fighting: 0.5,
  //   PokemonTypes.ground: 0.5,
  //   PokemonTypes.fire: 2,
  //   PokemonTypes.flying: 2,
  //   PokemonTypes.rock: 2,
  // },
  // PokemonTypes.rock: {
  //   PokemonTypes.normal: 0.5,
  //   PokemonTypes.fire: 0.5,
  //   PokemonTypes.poison: 0.5,
  //   PokemonTypes.flying: 0.5,
  //   PokemonTypes.water: 2,
  //   PokemonTypes.grass: 2,
  //   PokemonTypes.fighting: 2,
  //   PokemonTypes.ground: 2,
  //   PokemonTypes.steel: 2,
  // },
  // PokemonTypes.ghost: {
  //   PokemonTypes.normal: 0,
  //   PokemonTypes.fighting: 0,
  //   PokemonTypes.poison: 0.5,
  //   PokemonTypes.bug: 0.5,
  //   PokemonTypes.ghost: 2,
  //   PokemonTypes.dark: 2,
  // },
  // PokemonTypes.dragon: {
  //   PokemonTypes.fire: 0.5,
  //   PokemonTypes.water: 0.5,
  //   PokemonTypes.electric: 0.5,
  //   PokemonTypes.grass: 0.5,
  //   PokemonTypes.ice: 2,
  //   PokemonTypes.dragon: 2,
  //   PokemonTypes.fairy: 2,
  // },
  // PokemonTypes.dark: {
  //   PokemonTypes.psychic: 0,
  //   PokemonTypes.ghost: 0.5,
  //   PokemonTypes.dark: 0.5,
  //   PokemonTypes.fighting: 2,
  //   PokemonTypes.bug: 2,
  //   PokemonTypes.fairy: 2,
  // },
  // PokemonTypes.steel: {
  //   PokemonTypes.poison: 0,
  //   PokemonTypes.normal: 0.5,
  //   PokemonTypes.grass: 0.5,
  //   PokemonTypes.ice: 0.5,
  //   PokemonTypes.flying: 0.5,
  //   PokemonTypes.psychic: 0.5,
  //   PokemonTypes.bug: 0.5,
  //   PokemonTypes.rock: 0.5,
  //   PokemonTypes.dragon: 0.5,
  //   PokemonTypes.steel: 0.5,
  //   PokemonTypes.fairy: 0.5,
  //   PokemonTypes.fire: 2,
  //   PokemonTypes.fighting: 2,
  //   PokemonTypes.ground: 2,
  // },
  // PokemonTypes.fairy: {
  //   PokemonTypes.dragon: 0,
  //   PokemonTypes.fighting: 0.5,
  //   PokemonTypes.bug: 0.5,
  //   PokemonTypes.dark: 0.5,
  //   PokemonTypes.poison: 2,
  //   PokemonTypes.steel: 2,
  // },
};